### Webscraping Jobs on Indeed.com
August 2016
<br> Author: Peter Corniotes

#### Import Modules

In [1]:
import pandas as pd
import requests
import bs4
from bs4 import BeautifulSoup
import re

#### Function to Extract Job Title, Company, Job Summary, Location & Salary

In [2]:
#function to extract title, company, summary, location and salary

def jobs_scrape(soup):

#   extract titles        
    title = soup.findAll(class_='jobtitle')
    for i in title:
        try:
            titles.append(i.text.strip())
        except:
            titles.append(np.nan)

#   extract companies
    company = soup.findAll(class_='company')
    for i in company:
        try:
            companies.append(i.text.strip())
        except:
            companies.append(np.nan)            

#   extract summaries
    summary = soup.findAll(class_='summary')
    for i in summary:
        try:
            summaries.append(i.text)
        except:
            summaries.append(np.nan)            
                       
#   extract locations
    loc = soup.findAll(class_='location')
    for i in loc:
        try:
            locations.append(i.text)
        except:
            locations.append(np.nan)

#   extract salaries
    results = soup.findAll('div', class_ = "result")
    for i in results:
        salary_table = i.find('td', class_= "snip")
        if salary_table:
            salaries.append(salary_table.find('nobr'))
        else:
            salaries.append(np.nan)

#### Initialize Lists for Storing Results

In [3]:
titles = []
companies = []
summaries = []
locations = []
salaries = []

#### Search Items

In [4]:
# specify name of city
city = 'New+York'

#specify job title
job = 'data+scientist'

#specify maximum number of results
max_results = 500

#### Main Loop

In [5]:
increment = 10
for start in range(0, max_results, increment):
    URL = ('http://www.indeed.com/jobs?q='+job+'&l='+city+'&start='+str(start))
    r = requests.get(URL)
    soup = BeautifulSoup(r.content, "lxml")
    jobs_scrape(soup)

# confirm all lists have the same length
print 'list lengths', len(titles), len(companies), len(summaries), len(locations), \
len(salaries)

list lengths 750 750 750 750 750

#### Create Dataframe

In [6]:
df = pd.DataFrame([titles, companies, summaries, locations, salaries]).T
df.columns = ['title', 'company', 'summary', 'location', 'salary']

#Remove new line character from job summary text
df.summary = df.summary.apply(lambda x: re.sub('\n', '', x)) 
df

,title,company,summary,location,salary
0,Machine Learning Quantitative Analyst,Bloomberg,The Machine Learning Quantitative Analyst will...,"New York, NY",None
1,Data Engineer,Indeed,Work closely with stakeholders on the data dem...,"New York, NY 10036",None
2,Deep Learning Data Scientist,WorkFusion,Deep learning via multilayered neural networks...,"New York, NY",None
3,Data Scientist,Barclays,"Or Master’s Degree in operations research, app...","New York, NY",None
4,Data Scientist - Entry Level,Verizon,"Knowledge of machine learning, natural languag...","New York, NY 10003 (Greenwich Village area)",None
5,Data Scientist,Squarespace,Impressive skill with a major programming lang...,"New York, NY 10014 (West Village area)",None
6,"Data Scientist, Pricing & Yield",NBCUniversal,"Experience in handling large data sets, combin...","New York, NY",None
7,Data Scientist / Modeler,Morgan Stanley,The Modeling team and other MSSM project based...,"New York, NY 10032 (Washington Heights area)",None
8,Data Scientist,Quovo,We're looking for developers to expand a data ...,"New York, NY",None
9,Data Scientist,Verizon,Familiarity and experience with creating analy...,"New York, NY 10003 (Greenwich Village area)",None
10,Data Scientist,PlaceIQ,A mixture of analytical approaches are employe...,"New York, NY",None
11,Data Scientist,WebMD,"Medscape, a division of WebMD, develops and ho...","New York, NY",None
12,"Machine Learning Deployment Engineer, Professi...",Google,Experience with data analytics and/or data vis...,"New York, NY 10011 (Chelsea area)",None
13,Data Scientist - Relocation to China (Chinese ...,Booking.com,Data Scientist – China Localisation. Strong te...,"New York, NY",None
14,Economist,Gallup,Collaborate with Gallup’s senior scientists an...,"New York, NY",None
15,Machine Learning Quantitative Analyst,Bloomberg,The Machine Learning Quantitative Analyst will...,"New York, NY",None
16,Data Engineer,Indeed,Work closely with stakeholders on the data dem...,"New York, NY 10036",None
17,Deep Learning Data Scientist,WorkFusion,Deep learning via multilayered neural networks...,"New York, NY",None
18,Data Scientist II,MediaMath,Rapidly develop a deep understanding of the qu...,"New York, NY",None
19,Data Scientist,Macy's,(preferred) in relevant technical field such a...,"New York, NY",None
20,Data Scientist,"Syntel Inc.,",Senior Data Scientist. Developing data validat...,"New York, NY 10006 (Financial District area)",None
21,Data Scientist/Analyst,YouNow,Conduct in-depth research and analyses that tr...,"New York, NY",None
22,Data Scientist,Dia&Co,Dives deep into problems to truly understand t...,"New York, NY",None
23,Data Scientist,Amazon Corporate LLC,Leading in Machine Learning requires the best ...,"New York, NY",None
24,Data Scientist - USA,Dataiku,Familiarity with data visualization in R or Ja...,"New York, NY",None
25,Data Scientist,Astrid Solutions,Knowledge of current trends in Big Data framew...,"New York, NY",None
26,Data Scientist,Tilting Point,"As Data Scientist, you will work to ensure acc...","New York, NY",None
27,Data Scientist,Aetna,This position will use predictive and behavior...,"New York, NY 10010 (Gramercy area)",None
28,Data Scientist - Relocation to China (Chinese ...,Booking.com,Data Scientist – China Localisation. Strong te...,"New York, NY",None
29,Economist,Gallup,Collaborate with Gallup’s senior scientists an...,"New York, NY",None
...,...,...,...,...,...
720,Machine Learning Quantitative Analyst,Bloomberg,The Machine Learning Quantitative Analyst will...,"New York, NY",None
721,Data Engineer,Indeed,Work closely with stakeholders on the data dem...,"New York, NY 10036",None
722,Deep Learning Data Scientist,WorkFusion,Deep learning via multilayered neural networks...,"New York, NY",None
723,Chief Data Scientist - Consulting,Harnham,Chief Data Scientist - Consulting. Chief Data ...,"New York, NY","<nobr>$220,000 a year</nobr>"
724,Research Analyst,Counter Extremism Project,The Counter Extremism Project (CEP) is a not-f...,"New York, NY",None
725,"Director, Data Science",Integral Ad Science,Propose and develop solutions independently an...,"New York, NY",None
726,Director of Data Science,Movable Ink,Build and manage new data tables to support da...,"New York, NY",None
727,Quantitative Analyst,Next Step Systems,"Quantitative Analyst, New York City, NY New Yo...","New York, NY",None
728,Data Scientist - Quantitative Hedge Fund,NJF Search,"Experience with data analysis tools (R, numpy/...","New York, NY",None
729,Field Researcher,New York City Department of Health and Mental ...,"For Assignment Level I (only physical, biologi...","Long Island City, NY 11101","<nobr>$68,239 a year</nobr>"
730,"Technical Curriculum Developer, Google Cloud P...",Google,"As a Technical Curriculum Developer, you will ...","New York, NY 10011 (Chelsea area)",None
731,Research Analyst,Cumulus Media,Qualifications | Competency 1 year of experien...,"New York, NY",None
732,Lead Data Scientist,ADP,"Deep understanding of Excel, SQL, Oracle for d...","Roseland, NJ 07068",None
733,Data Scientist - Relocation to China (Chinese ...,Booking.com,Data Scientist – China Localisation. Strong te...,"New York, NY",None
734,Economist,Gallup,Collaborate with Gallup’s senior scientists an...,"New York, NY",None
735,Machine Learning Quantitative Analyst,Bloomberg,The Machine Learning Quantitative Analyst will...,"New York, NY",None
736,Data Engineer,Indeed,Work closely with stakeholders on the data dem...,"New York, NY 10036",None
737,Deep Learning Data Scientist,WorkFusion,Deep learning via multilayered neural networks...,"New York, NY",None
738,Sr. Statistical Programmer,Novella Clinical,"Input to project timelines, and ensure that pr...","New York, NY",None
739,Data Scientist Director - East,Avanade,About the Data Scientist role. Microsoft SQL S...,"New York, NY",None
740,Research Scientist: Control Systems,AreteX Systems,The successful candidate will work closely wit...,"New York, NY",None
741,"Software Development Engineer, Data Science","Audible, Inc.",Do you enjoy working with Data Scientists to w...,"Newark, NJ",None
742,Lead Data Scientist,ISO,"Lead Data Scientist. Follows, and may create, ...","Jersey City, NJ",None
743,Sr Data Engineer,The Hackerati,"Our team of Developers, Designers and Scientis...","New York, NY",None
744,Revenue Management Analyst - Process Improvement,NYU Langone Medical Center,"And Hassenfeld Children’s Hospital, a comprehe...","New York, NY",None
745,Senior Data Scientist,FIS,Capco is looking for Senior Data Scientists. S...,"New York, NY 10034 (Inwood area)",None
746,Software Engineer - Machine Learning and Langu...,FactSet Research Systems,The primary responsibility for this position w...,"New York, NY 10016 (Gramercy area)",None
747,"Product Manager, Enterprise Informatics",Schrodinger,Our mission is to dramatically improve human h...,"New York, NY",None
748,Data Scientist - Relocation to China (Chinese ...,Booking.com,Data Scientist – China Localisation. Strong te...,"New York, NY",None
749,Economist,Gallup,Collaborate with Gallup’s senior scientists an...,"New York, NY",None

#### Create CSV File

In [7]:
df.to_csv('/Users/petercorniotes/Downloads/search_results.csv', encoding='utf-8')